In [1]:
import pandas as pd
from pathlib import Path
dir = Path("../GFQA_v3")
dir

WindowsPath('../GFQA_v3')

In [2]:
df = pd.read_csv(dir / "GEMStat_parameter_metadata.csv", encoding="ISO-8859-1")
df.head()

,Parameter Code,Parameter Name,Parameter Long Name,Parameter Group,EC Number,CAS Number,ChEBI Number,Parameter Description
0,1112TTCETA,Tetrachloroethane,"1,1,1,2-Tetrachloroethane",/Chemical/Organic/Halocarbon,211-135-1,630-20-6,34024,"1,1,1,2-Tetrachloroethane is a chlorinated hyd..."
1,111TCA,Methyl Chloroform,"1,1,1-Trichloroethane",/Chemical/Organic/Volatile Organic Compound,200-756-3,71-55-6,36015,C2H3Cl3 | A chloroalkane also known as methyl ...
2,1122TTCETA,Tetrachloroethane,"1,1,2,2-Tetrachloroethane",/Chemical/Organic/Halocarbon,201-197-8,79-34-5,36026,"1,1,2,2-Tetrachloroethane is a chlorinated der..."
3,112TCA,"1,1,2-TCA","1,1,2-Trichloroethane",/Chemical/Organic/Volatile Organic Compound,201-166-9,79-00-5,36018,C2H3Cl3 | An organochloride solvent. It is use...
4,11DCA,"1,1-DCA","1,1-Dichloroethane",/Chemical/Organic/Volatile Organic Compound,200-863-5,75-34-3,81599,CH3CHCl2 | A colorless oily liquid with a chlo...

In [3]:
params = list(set(df["Parameter Name"]))
print(f"Se Registran {len(params)} Parametros\n")

for i, p in enumerate(params):
	print(f"{i+1}) {p}")

Se Registran 294 Parametros

1) Sulfonylurea
2) Ketone
3) Tetralin
4) Rubidium
5) Methyl Chloride
6) Mesophiles
7) Nickel
8) Oil and Grease
9) Absorbance
10) Detergents
11) Uranium
12) Heptachlor
13) Coliforms
14) Benzo[k]fluoranthene
15) Endosulfan
16) Trihalomethanes
17) 1,1-DCA
18) Methylnaphthalene
19) Electrical Conductance
20) Hydrocarbons
21) Carbohydrazide
22) Pentachlorobenzene
23) Silver
24) Mercury
25) Caesium
26) Chlordane
27) DDE
28) Bromacil
29) Glyphosate
30) HCB
31) Arsenic
32) Methylene Dichloride
33) Benzene
34) Cypermethrin
35) Methoxychlor
36) Anionic Tensides
37) Trichlorobenzene
38) PFOA
39) Total Nitrogen
40) Oxygen Demand
41) Dieldrin
42) Dichlorvos
43) Inorganic Carbon
44) Dowicide 2
45) Aldicarb
46) Fluoride
47) Phytoplankton
48) O-Phenylenpyrene
49) Tin
50) Dinitroaniline
51) Phthalate
52) Carbamate
53) Bromide
54) Trichloroacetic Acid
55) Diflufenican
56) Urea
57) Nitroamine
58) Strontium
59) Vinyl chloride
60) Sulfate
61) Molybdenum
62) Terbutryn
63) Inorganic Nitrogen
64) Enilconazole
65) Carbon
66) Triazine
67) Acenaphthene
68) Tetrachlorobenzene
69) Benzamide
70) Isopropylbenzene
71) Clopyralid
72) Chloride
73) Nitrochlorobenzene
74) Organic Carbon
75) 1,1,2-TCA
76) Dichloroaniline
77) Oxamyl
78) Naphtalene
79) Bromoxynil
80) Beryllium
81) Phenylurea
82) Gallium
83) Metribuzin
84) PFOS
85) Petroleum Hydrocarbons
86) Alachlor
87) Fenoxaprop-ethyl
88) Triazole
89) Cerium
90) Antimony
91) Dissolved Solids
92) Prometryn
93) Methyl Chloroform
94) Hydroxide
95) Bismuth
96) Chloroethene
97) Tetraphene
98) Acetochlor
99) Methyl Bromide
100) Chlorophyll A
101) Mecoprop
102) Phosphorus
103) 2-Chlorotoluene
104) Thiocarbamate
105) Calcium
106) Dichlorophenyl
107) 2,4-MCPB
108) 1-Naphthol
109) Silicate
110) Niobium
111) Tricyclazole
112) Tungsten
113) Anthracene
114) Nitrobenzoic Acid
115) Xylene
116) Benzo[jk]fluorene
117) Ethalfluralin
118) Terbuthylazine
119) Anti-Inflammatory Drug
120) Cobalt
121) Rhothane
122) Pyrethroid ester
123) Carbon Dioxide
124) Titanium
125) Mitotane
126) PCP
127) Bromine
128) Selenium
129) Chloroalkanes
130) Ethylbenzene
131) Polyaromatic Hydrocarbons
132) Dimethomorph
133) Silicon
134) Ethylene Dichloride
135) Manganese
136) 2,4-DB
137) Aldrin
138) Barium
139) Hardness
140) Perylene
141) 2,4,5-TP
142) Ametryn
143) Bicarbonate
144) Color
145) PCB
146) Styrene
147) Cadmium
148) Sulcotrione
149) Thallium
150) Dalapon
151) Chloroethenes
152) Benzopyrene
153) Dichlorobromomethane
154) Tetrachloroethane
155) Dibromochloromethane
156) Metalaxyl
157) Halomethane
158) Bentazone
159) Dicamba
160) Allyltrichlorid
161) Strobilurin
162) Oxazolidinone
163) Indene
164) Chlorfenvinphos
165) Carbendazim
166) Salinity
167) Demeton-S-methyl
168) Boron
169) Benzene Chloride
170) Benzodioxole
171) Benzenamine
172) Suspended Solids
173) Anniline
174) Nitrobenzene
175) PCN
176) Phenanthrene
177) Turbidity
178) Lanthanum
179) Dimethenamid
180) 2,4,5-T
181) Organothiophosphate
182) Pyrimidine
183) Organic Halogen
184) Lithium
185) Esters
186) Organotin Compound
187) Benzothiazole
188) pH
189) Zinc
190) Dichlorobenzene
191) Acrylonitrile
192) PBDE
193) Methomyl
194) Cyclodiene Pesticide
195) Orthophosphate
196) Aluminium
197) Carbaryl
198) Dichlobenil
199) Carbonate
200) Picolinafen
201) Toxaphene
202) Phosphonic acids
203) Alkalinity
204) Captafol
205) Flurtamone
206) Mirex
207) Total Solids
208) Acrolein
209) 3-Methylcholanthrene
210) Propazine
211) Carbazole
212) Antilipidemic Drug
213) BHC
214) Carbon Tetrachloride
215) Thiadiazole
216) Phosmet
217) Temperature
218) Chlorpyrifos
219) Enterococci
220) Ammonia
221) Potassium
222) Yttrium
223) Dicofol
224) DDD
225) Anilide
226) Organophosphate
227) Dowicide 2s
228) Benzo[ghi]perylene
229) Phosalone
230) SCCP
231) Isoproturon
232) Chloroacetic acid
233) Transparency
234) Pyridines
235) Dacthal
236) Kjeldahl Nitrogen
237) Organic Nitrogen
238) Magnesium
239) Sodium
240) Pentachloronitrobenzene
241) Picloram
242) 2,4-DP
243) Antibiotic
244) Dibenz[a,h]anthracene
245) Fipronil
246) Nitrophenyl Ether
247) Discharge
248) Chloroform
249) Oxidized Nitrogen
250) Bromoform
251) Cyclopenta[de]naphthalene
252) Captan
253) DDT
254) Toluene
255) Benzofuran
256) Fluorene
257) Heptachlor Epoxide
258) Chlordecone
259) Lead
260) PCA
261) Sulfur
262) Nonachlor
263) Benzo[b]fluoranthene
264) Benzo[e]pyrene
265) Vanadium
266) Chromium
267) Iron
268) Hydrogen Sulphide
269) Copper
270) Chrysene
271) Morpholine
272) Imidazolinone
273) Methyl tert-butyl ether
274) Pirimicarb
275) Neonicotinoid
276) Platinum
277) Dibromochloropropane
278) Biphenyl
279) Propylene Dichloride
280) Dinoseb
281) Benzoic Acid
282) 2,4-D
283) Organochlorine
284) Bromochloromethane
285) Cyanide
286) Phenol
287) Phosphate
288) Endrin
289) Streptococci
290) Beta Blocker
291) Phosphinothricin
292) MCPA
293) Oxygen
294) Simazine

In [4]:
clorofila = ""
for p in list(df["Parameter Name"]):
	if p.lower().startswith("chlorophyll"):
		clorofila = p
clorofila

'Chlorophyll A'

In [5]:
c = df[df["Parameter Name"] == clorofila]
c
#clorofila_code = str(c["Parameter Code"])
#clorofila_code

,Parameter Code,Parameter Name,Parameter Long Name,Parameter Group,EC Number,CAS Number,ChEBI Number,Parameter Description
183,Chl-a,Chlorophyll A,Chlorophyll A,/Biological/Pigment,207-536-6,479-61-8,1823,"C55H72MgN4O5, [(2E,7R,11R)-3,7,11,15-tetrameth..."

In [6]:
chla_code = c["Parameter Code"].item()
param_group = c["Parameter Group"].item()

print(f"Grupo De Parametros: {param_group}")
print(f"Clorofila-a Codigo: {chla_code}")

Grupo De Parametros: /Biological/Pigment
Clorofila-a Codigo: Chl-a

In [7]:
pigments = pd.read_csv(dir / "Pigment.csv", encoding="ISO-8859-1")
pigments.head()

C:\Users\User\AppData\Local\Temp\ipykernel_3972\204426523.py:1: DtypeWarning: Columns (0: Analysis Method Code) have mixed types. Specify dtype option on import or set low_memory=False.
  pigments = pd.read_csv(dir / "Pigment.csv", encoding="ISO-8859-1")

,GEMS Station Number,Sample Date,Sample Time,Depth,Parameter Code,Analysis Method Code,Value Flags,Value,Unit,Data Quality,Integrated Value,Remark,License Information
0,AUT00235,2010-01-13,12:00,0.3,Chl-a,0,NaN,0.0050,mg/l,Fair,NaN,NaN,NaN
1,AUT00235,2010-02-09,12:00,0.3,Chl-a,0,NaN,0.0055,mg/l,Fair,NaN,NaN,NaN
2,AUT00235,2010-03-08,12:00,0.3,Chl-a,0,NaN,0.0146,mg/l,Fair,NaN,NaN,NaN
3,AUT00235,2010-04-06,12:00,0.3,Chl-a,0,NaN,0.0056,mg/l,Fair,NaN,NaN,NaN
4,AUT00235,2010-05-06,12:00,0.3,Chl-a,0,NaN,0.0038,mg/l,Fair,NaN,NaN,NaN

In [9]:
# contar cuantos registros hay de este parametro en uruguay despues del 2015
def uy_param_count_after_2015(param_code, dataset, countries = ("URY")):
	param_only = dataset[dataset["Parameter Code"] == param_code]
	param_only_uy = param_only[param_only['GEMS Station Number'].str.startswith(countries, na=False)]
	param_only_uy_post_2015 = param_only_uy[pd.to_datetime(param_only_uy['Sample Date']).dt.year >= 2015]
	total_params = len(param_only_uy_post_2015)
	total_stations = len(param_only_uy_post_2015["GEMS Station Number"].unique())
	return total_params, total_stations

In [10]:
cant_clorofila_a = uy_param_count_after_2015(param_code=chla_code, dataset=pigments)
cant_clorofila_a

(3806, 155)

In [11]:
for p in list(df["Parameter Name"]):
	if "sus" in p.lower():
		print(p)

Suspended Solids
Suspended Solids
Suspended Solids

In [12]:
df[df["Parameter Name"] == "Suspended Solids"]

,Parameter Code,Parameter Name,Parameter Long Name,Parameter Group,EC Number,CAS Number,ChEBI Number,Parameter Description
292,FSS,Suspended Solids,Fixed Suspended Solids,/Physical/Water/Solids,NaN,NaN,NaN,Residue of solids that are retained by a filte...
589,TSS,Suspended Solids,Total Suspended Solids,/Physical/Water/Solids,NaN,NaN,NaN,Portion of solids retained by a filter.
606,VSS,Suspended Solids,Volatile Suspended Solids,/Physical/Water/Solids,NaN,NaN,NaN,Weight loss of total suspended solid fraction ...

In [13]:
water = pd.read_csv(dir/"Water.csv")
cant_tts = uy_param_count_after_2015(param_code="TSS", dataset=water)
cant_tts

C:\Users\User\AppData\Local\Temp\ipykernel_3972\3489920704.py:1: DtypeWarning: Columns (0: Analysis Method Code) have mixed types. Specify dtype option on import or set low_memory=False.
  water = pd.read_csv(dir/"Water.csv")

(2231, 168)

In [14]:
df[df["Parameter Name"] == "Transparency"]

,Parameter Code,Parameter Name,Parameter Long Name,Parameter Group,EC Number,CAS Number,ChEBI Number,Parameter Description
579,TRANS,Transparency,Transparency,/Physical/Optical,NaN,NaN,NaN,Measure of the depth of light penetration into...

In [15]:
df[df["Parameter Name"] == "Phytoplankton"]

,Parameter Code,Parameter Name,Parameter Long Name,Parameter Group,EC Number,CAS Number,ChEBI Number,Parameter Description
492,Phyt-B,Phytoplankton,Phytoplankton Biomass,/Biological/Phytoplankton,NaN,NaN,NaN,NaN

In [16]:
for p in params:
	if "turbidity" in p.lower():
		print(p)

Turbidity

In [17]:
turbidity = df[df["Parameter Name"] == "Turbidity"]
turbidity

,Parameter Code,Parameter Name,Parameter Long Name,Parameter Group,EC Number,CAS Number,ChEBI Number,Parameter Description
590,TURB,Turbidity,Turbidity,/Physical/Optical,NaN,NaN,NaN,Cloudiness or haziness of a fluid caused by su...

In [18]:
cant_turbidity = uy_param_count_after_2015(param_code=turbidity["Parameter Code"].item(), dataset=pd.read_csv(dir/"Optical.csv"))
cant_turbidity

C:\Users\User\AppData\Local\Temp\ipykernel_3972\2107825658.py:1: DtypeWarning: Columns (0: Analysis Method Code, 1: Value Flags) have mixed types. Specify dtype option on import or set low_memory=False.
  cant_turbidity = uy_param_count_after_2015(param_code=turbidity["Parameter Code"].item(), dataset=pd.read_csv(dir/"Optical.csv"))

(8483, 222)

In [21]:
param_count = []
station_count = []

params_of_interest = [
	("TURB", "Optical.csv"),
	("TSS", "Water.csv"),
	("Chl-a", "Pigment.csv"),
	("TRANS", "Optical.csv"),
	#("Phyt-B", "Phytoplankton.csv")
]

for p in params_of_interest:
	param_code, fname = p[0], p[1]
	count = uy_param_count_after_2015(
		param_code,
		dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
		countries=("URY")
	)
	print(count)
	param_count.append(count[0])
	station_count.append(count[1])
	#print(count)

C:\Users\User\AppData\Local\Temp\ipykernel_3972\4131898569.py:16: DtypeWarning: Columns (0: Analysis Method Code, 1: Value Flags) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),

(8483, 222)

C:\Users\User\AppData\Local\Temp\ipykernel_3972\4131898569.py:16: DtypeWarning: Columns (0: Analysis Method Code) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),

(2231, 168)
(3806, 155)

C:\Users\User\AppData\Local\Temp\ipykernel_3972\4131898569.py:16: DtypeWarning: Columns (0: Analysis Method Code) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),

(2184, 96)

C:\Users\User\AppData\Local\Temp\ipykernel_3972\4131898569.py:16: DtypeWarning: Columns (0: Analysis Method Code, 1: Value Flags) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),

In [22]:
print("Total parametros en Uruguay despues del 2015")

param_names = []

for p in params_of_interest:
	param_names.append(df[df["Parameter Code"] == p[0]]["Parameter Name"].item())


total_params = {
	"Code": [p[0] for p in params_of_interest] + ["Total"],
	"Parametro": param_names + [len(param_names)],
	"Cant": param_count + [sum(param_count)],
	"Cant Stations": station_count + [sum(station_count)]
}

total_df = pd.DataFrame(total_params)
total_df

Total parametros en Uruguay despues del 2015

    Code         Parametro   Cant  Cant Stations
0   TURB         Turbidity   8483            222
1    TSS  Suspended Solids   2231            168
2  Chl-a     Chlorophyll A   3806            155
3  TRANS      Transparency   2184             96
4  Total                 4  16704            641

In [23]:
total_df.to_csv("total_param_remote_sensing.csv")