In [1]:
import pandas as pd
from pathlib import Path
dir = Path("../GFQA_v3")
dir

WindowsPath('../GFQA_v3')

In [2]:
df = pd.read_csv(dir / "GEMStat_parameter_metadata.csv", encoding="ISO-8859-1")
df.head()

,Parameter Code,Parameter Name,Parameter Long Name,Parameter Group,EC Number,CAS Number,ChEBI Number,Parameter Description
0,1112TTCETA,Tetrachloroethane,"1,1,1,2-Tetrachloroethane",/Chemical/Organic/Halocarbon,211-135-1,630-20-6,34024,"1,1,1,2-Tetrachloroethane is a chlorinated hyd..."
1,111TCA,Methyl Chloroform,"1,1,1-Trichloroethane",/Chemical/Organic/Volatile Organic Compound,200-756-3,71-55-6,36015,C2H3Cl3 | A chloroalkane also known as methyl ...
2,1122TTCETA,Tetrachloroethane,"1,1,2,2-Tetrachloroethane",/Chemical/Organic/Halocarbon,201-197-8,79-34-5,36026,"1,1,2,2-Tetrachloroethane is a chlorinated der..."
3,112TCA,"1,1,2-TCA","1,1,2-Trichloroethane",/Chemical/Organic/Volatile Organic Compound,201-166-9,79-00-5,36018,C2H3Cl3 | An organochloride solvent. It is use...
4,11DCA,"1,1-DCA","1,1-Dichloroethane",/Chemical/Organic/Volatile Organic Compound,200-863-5,75-34-3,81599,CH3CHCl2 | A colorless oily liquid with a chlo...

In [12]:
params = list(set(df["Parameter Name"]))
print(f"Se Registran {len(params)} Parametros\n")

s = ""
for i, p in enumerate(params):
	s+= f"{i+1}) {p}\n"

with open("stations_param_list.txt", "w") as f:
	f.write(s)

Se Registran 294 Parametros

In [93]:
f = df[df["Parameter Name"] == "Electrical Conductance"]
f

,Parameter Code,Parameter Name,Parameter Long Name,Parameter Group,EC Number,CAS Number,ChEBI Number,Parameter Description
253,EC,Electrical Conductance,Electrical Conductance,/Chemical/Inorganic/Bulk Property,NaN,NaN,NaN,Measure of the ability of water to carry an el...

In [90]:
# contar cuantos registros hay de este parametro en uruguay despues del 2015
def uy_param_count_after_2015(param_code, dataset, after=2015, countries = ("URY")):
	param_only = dataset[dataset["Parameter Code"] == param_code]
	param_only_uy = param_only[param_only['GEMS Station Number'].str.startswith(countries, na=False)]
	param_only_uy_post_2015 = param_only_uy[pd.to_datetime(param_only_uy['Sample Date']).dt.year >= after]
	total_params = len(param_only_uy_post_2015)
	stations = param_only_uy_post_2015["GEMS Station Number"].unique()
	#total_stations = len()
	return total_params, stations

In [56]:
#cant_ph = uy_param_count_after_2015(param_code="pH", dataset=
#cant_ph
a = pd.read_csv(dir/"Organic.csv",  encoding="ISO-8859-1")
a_uy = a[a['GEMS Station Number'].str.startswith(("URY"), na=False)]
a_uy["Parameter Code"].unique()
#cant_clorofila_a

C:\Users\User\AppData\Local\Temp\ipykernel_35212\3900846673.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  a = pd.read_csv(dir/"Organic.csv",  encoding="ISO-8859-1")

array(['AOX', 'OG'], dtype=object)

In [119]:
params_of_interest = [
    ("pH", ["pH.csv"]),
    ("ECOLI", ["Indicator_Organism.csv"]),
    ("FECALCOLI", ["Indicator_Organism.csv"]),
    ("TOTCOLI", ["Indicator_Organism.csv"]),
    ("TOTMESO", ["Indicator_Organism.csv"]),
    ("ENTCOCC", ["Indicator_Organism.csv"]),
    ("FECALSTREP", ["Indicator_Organism.csv"]),
    ("BOD", ["Oxygen_Demand.csv"]),
    ("COD", ["Oxygen_Demand.csv"]),
    ("PV", ["Oxygen_Demand.csv"]),
    ("O2-Dis", ["Dissolved_Gas.csv"]),
    ("O2-Dis-Sat", ["Dissolved_Gas.csv"]),
    ("NH3N", ["Other_Nitrogen.csv", "Oxidized_Nitrogen.csv"]),
    ("NH4N", ["Other_Nitrogen.csv", "Oxidized_Nitrogen.csv"]),
	("TDP", ["Phosphorus.csv"]),
	("TP", ["Phosphorus.csv"]),
	("TPP", ["Phosphorus.csv"]),
    ("PN", ["Other_Nitrogen.csv", "Oxidized_Nitrogen.csv"]),
    ("TN", ["Other_Nitrogen.csv", "Oxidized_Nitrogen.csv"]),
    ("TDN", ["Other_Nitrogen.csv", "Oxidized_Nitrogen.csv"]),
	("TEMP", ["Temperature.csv"]),
	("EC", ["Electrical_Conductance.csv"])
]

In [120]:
param_counts = []
station_counts= []
stay_params = []
total_unique_stations = set()

for p in params_of_interest:
	param_code, files= p[0], p[1]

	param_count = 0
	station_count = 0

	for fname in files:
		count, stations = uy_param_count_after_2015(
			param_code,
			dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
			after=2015,
			countries=("URY")
		)

		param_count += count
		station_count += len(stations)

		for station in list(stations):
			total_unique_stations.add(station)

	if param_count > 0:
		param_counts.append(param_count)
		station_counts.append(station_count)
		stay_params.append(param_code)

C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,11) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,11) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,11) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,11) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,11) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,11) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,6,11) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,6,11) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,11) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,6,11) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,11) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,6,11) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,11) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,11) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,11) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,11) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,6,11) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,11) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,6,11) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,11) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,6,11) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),
C:\Users\User\AppData\Local\Temp\ipykernel_35212\1963907875.py:15: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset=pd.read_csv(dir/fname, encoding="ISO-8859-1"),

In [123]:
print("Total parametros en Uruguay despues del 2015")

param_names = []

for p in stay_params:
	param_names.append(df[df["Parameter Code"] == p]["Parameter Name"].item())

total_params = {
	"Code": [p for p in stay_params] + ["Total"],
	"Parametro": param_names + ["Total"],
	"Cantidad": param_counts + [sum(param_counts)],
	"Estaciones": station_counts + [len(total_unique_stations)]
}

total_df = pd.DataFrame(total_params)
total_df

Total parametros en Uruguay despues del 2015

          Code               Parametro  Cantidad  Estaciones
0           pH                      pH     10183         238
1        ECOLI               Coliforms       985          42
2    FECALCOLI               Coliforms      4865         179
3      TOTCOLI               Coliforms       722          31
4          BOD           Oxygen Demand      1626         143
5          COD           Oxygen Demand       309          50
6       O2-Dis                  Oxygen      7217         223
7   O2-Dis-Sat                  Oxygen      4693         182
8         NH4N                 Ammonia      3667         172
9           TP              Phosphorus      4330         183
10          TN          Total Nitrogen      3996         182
11        TEMP             Temperature      9897         233
12          EC  Electrical Conductance      9598         237
13       Total                   Total     62088         238

In [126]:
total_df.to_csv("total_params_in_situ.csv")