#

In [2]:
#import geopandas as geo
import pandas as pd

In [3]:
df = pd.read_csv("datasets/grillas/inia_gras_ibh2025.csv")

In [4]:
#metadatos = geo.read_file("datasets/grillas/metadatos_inia_ibh_por_grilla.json")

In [5]:
df.head()

,id,Longitud,Latitud,2025_011,2025_012,2025_013,2025_010,2025_021,2025_022,2025_023,...,2025_103,2025_100,2025_111,2025_112,2025_113,2025_110,2025_121,2025_122,2025_123,2025_120
0,0,-58.3335,-34.3335,44.093086,50.057945,46.926395,47.022602,55.353222,78.949310,86.827492,...,84.465073,87.344475,83.332275,80.154785,75.743927,79.743660,70.224083,69.450729,53.856770,64.166855
1,1,-58.0000,-34.3335,35.933353,40.733299,52.120384,43.225510,62.594631,78.071442,84.515945,...,82.806541,86.437096,77.810364,75.246193,72.772720,75.276428,68.780899,55.395668,37.541302,53.378063
2,2,-58.3335,-34.0000,33.813568,40.265263,42.964825,39.141979,59.270447,79.005669,86.556381,...,84.445236,86.282066,80.598244,83.097298,79.554955,81.083496,73.763382,66.927856,46.934879,62.038586
3,3,-58.0000,-34.0000,33.130894,39.456367,41.439236,38.119492,59.634979,76.287521,78.027473,...,82.589813,85.590256,77.166946,79.708458,74.140434,77.005280,68.304375,52.428703,36.674797,51.959793
4,4,-57.6665,-34.3335,27.766127,30.070860,50.224262,36.478603,69.234711,75.177559,73.261284,...,81.633507,85.742920,74.703522,72.740845,75.224243,74.222870,64.578918,47.845230,25.843422,45.436100

In [6]:
df[["Longitud", "Latitud"]] #;

     Longitud  Latitud
0    -58.3335 -34.3335
1    -58.0000 -34.3335
2    -58.3335 -34.0000
3    -58.0000 -34.0000
4    -57.6665 -34.3335
..        ...      ...
174  -54.0000 -33.3335
175  -53.6665 -33.6665
176  -55.6665 -32.3335
177  -55.3335 -32.3335
178  -57.0000 -34.0000

[179 rows x 2 columns]

Los valores de IBH promedio, asociados a la celda, se presentan en columnas decadiales y mensuales. Los nombres de estas columnas siguen el formato `yyyy_mmd`, donde `yyyy` corresponde al año, `mm` corresponde al mes y `d` corresponde a la década del mes.Se utiliza 1 para los primeros diez días, 2 para los días 11 al 20 y 3 para los días del 21 al final del mes.Cuando `d` es 0, el valor corresponde al promedio mensual."

In [7]:
df[:1] ---- >

SyntaxError: invalid syntax (471809026.py, line 1)

In [8]:
#44
#50

In [9]:
#fila = df[:1]
#longitud = float(fila["Longitud"].iloc[0])
#latitud = float(fila["Latitud"].iloc[0])
#latitud
#df[:1]["Longitud"]

In [10]:
df_2 = df.copy()
df_2 = df_2.drop(columns=["id"]) # aca
df_2

,Longitud,Latitud,2025_011,2025_012,2025_013,2025_010,2025_021,2025_022,2025_023,2025_020,...,2025_103,2025_100,2025_111,2025_112,2025_113,2025_110,2025_121,2025_122,2025_123,2025_120
0,-58.3335,-34.3335,44.093086,50.057945,46.926395,47.022602,55.353222,78.949310,86.827492,72.773048,...,84.465073,87.344475,83.332275,80.154785,75.743927,79.743660,70.224083,69.450729,53.856770,64.166855
1,-58.0000,-34.3335,35.933353,40.733299,52.120384,43.225510,62.594631,78.071442,84.515945,74.385300,...,82.806541,86.437096,77.810364,75.246193,72.772720,75.276428,68.780899,55.395668,37.541302,53.378063
2,-58.3335,-34.0000,33.813568,40.265263,42.964825,39.141979,59.270447,79.005669,86.556381,74.114723,...,84.445236,86.282066,80.598244,83.097298,79.554955,81.083496,73.763382,66.927856,46.934879,62.038586
3,-58.0000,-34.0000,33.130894,39.456367,41.439236,38.119492,59.634979,76.287521,78.027473,70.837311,...,82.589813,85.590256,77.166946,79.708458,74.140434,77.005280,68.304375,52.428703,36.674797,51.959793
4,-57.6665,-34.3335,27.766127,30.070860,50.224262,36.478603,69.234711,75.177559,73.261284,72.507607,...,81.633507,85.742920,74.703522,72.740845,75.224243,74.222870,64.578918,47.845230,25.843422,45.436100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,-54.0000,-33.3335,41.006100,41.921803,51.123421,44.891506,52.646145,77.660576,82.871346,70.215637,...,73.155914,74.286522,69.927795,68.055077,52.336987,63.439953,57.691784,62.873127,61.962925,60.878750
175,-53.6665,-33.6665,53.291130,55.347603,49.226677,52.512283,52.753632,64.458527,64.847717,60.389404,...,76.431793,77.215942,75.280052,69.377113,53.747589,66.134918,53.474159,49.284279,41.678467,47.937016
176,-55.6665,-32.3335,53.515602,63.754253,65.394684,61.033550,55.884327,82.859566,87.534203,74.561165,...,80.058105,84.923637,77.928917,81.079613,71.226158,76.744896,67.056763,73.966606,66.853233,69.213524
177,-55.3335,-32.3335,57.744080,64.123718,58.495888,60.068798,51.794415,77.496384,81.627426,69.497406,...,76.547218,80.383583,73.979897,77.459007,70.081779,73.840225,66.584839,71.373322,65.760353,67.836952
178,-57.0000,-34.0000,40.941998,33.968163,61.369278,45.940765,63.563171,76.393600,86.095901,74.583389,...,75.039490,80.434311,69.146645,69.564087,65.464714,68.058479,51.072136,58.329884,30.211380,46.011139

In [11]:
columnas_de_promedios = []

for i in range(5, 50, 4):
    columna = df_2.columns[i]
    columnas_de_promedios.append(columna)

columnas_de_promedios

df_2 = df_2.drop(columns = columnas_de_promedios)
df_2

,Longitud,Latitud,2025_011,2025_012,2025_013,2025_021,2025_022,2025_023,2025_031,2025_032,...,2025_093,2025_101,2025_102,2025_103,2025_111,2025_112,2025_113,2025_121,2025_122,2025_123
0,-58.3335,-34.3335,44.093086,50.057945,46.926395,55.353222,78.949310,86.827492,97.453812,87.844139,...,96.212311,93.745445,84.110855,84.465073,83.332275,80.154785,75.743927,70.224083,69.450729,53.856770
1,-58.0000,-34.3335,35.933353,40.733299,52.120384,62.594631,78.071442,84.515945,97.780418,88.231819,...,96.243515,93.414093,83.453705,82.806541,77.810364,75.246193,72.772720,68.780899,55.395668,37.541302
2,-58.3335,-34.0000,33.813568,40.265263,42.964825,59.270447,79.005669,86.556381,97.968742,87.838783,...,95.657066,92.798080,81.786568,84.445236,80.598244,83.097298,79.554955,73.763382,66.927856,46.934879
3,-58.0000,-34.0000,33.130894,39.456367,41.439236,59.634979,76.287521,78.027473,97.839584,87.003586,...,95.743652,92.945999,81.534996,82.589813,77.166946,79.708458,74.140434,68.304375,52.428703,36.674797
4,-57.6665,-34.3335,27.766127,30.070860,50.224262,69.234711,75.177559,73.261284,97.453743,87.313469,...,96.316086,93.250900,82.755302,81.633507,74.703522,72.740845,75.224243,64.578918,47.845230,25.843422
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,-54.0000,-33.3335,41.006100,41.921803,51.123421,52.646145,77.660576,82.871346,92.778824,88.012215,...,82.936249,79.596458,70.220238,73.155914,69.927795,68.055077,52.336987,57.691784,62.873127,61.962925
175,-53.6665,-33.6665,53.291130,55.347603,49.226677,52.753632,64.458527,64.847717,61.123253,73.682297,...,82.065941,80.668381,74.626060,76.431793,75.280052,69.377113,53.747589,53.474159,49.284279,41.678467
176,-55.6665,-32.3335,53.515602,63.754253,65.394684,55.884327,82.859566,87.534203,93.349312,78.756218,...,95.521187,93.543579,81.655792,80.058105,77.928917,81.079613,71.226158,67.056763,73.966606,66.853233
177,-55.3335,-32.3335,57.744080,64.123718,58.495888,51.794415,77.496384,81.627426,93.699837,80.490814,...,88.539825,87.101624,77.885559,76.547218,73.979897,77.459007,70.081779,66.584839,71.373322,65.760353
178,-57.0000,-34.0000,40.941998,33.968163,61.369278,63.563171,76.393600,86.095901,96.012665,82.048508,...,90.674438,89.898964,76.903961,75.039490,69.146645,69.564087,65.464714,51.072136,58.329884,30.211380

In [12]:
df_2.columns

Index(['Longitud', 'Latitud', '2025_011', '2025_012', '2025_013', '2025_021',
       '2025_022', '2025_023', '2025_031', '2025_032', '2025_033', '2025_041',
       '2025_042', '2025_043', '2025_051', '2025_052', '2025_053', '2025_061',
       '2025_062', '2025_063', '2025_071', '2025_072', '2025_073', '2025_081',
       '2025_082', '2025_083', '2025_091', '2025_092', '2025_093', '2025_101',
       '2025_102', '2025_103', '2025_111', '2025_112', '2025_113', '2025_121',
       '2025_122', '2025_123'],
      dtype='object')

In [13]:
import calendar
def parse_date_column(column: str):
    parts = column.split("_")
    
    # yyyy_mmd
    # 1 -> 1-10
    # 2 -> 11 - 20
    # 3 -> 21 - fin_mes 
    
    year = int(parts[0])
    mes = int(parts[1][:2])
    periodo = int(parts[1][-1])
    
    if periodo == 1:
        fecha_inicio = pd.Timestamp(year=year, month=mes, day=1, hour=0, minute=0, second=0)
        fecha_fin = pd.Timestamp(year=year, month=mes, day=10, hour=23, minute=59, second=59)
        return fecha_inicio, fecha_fin
    elif periodo == 2:
        fecha_inicio = pd.Timestamp(year=year, month=mes, day=11, hour=0, minute=0, second=0)
        fecha_fin = pd.Timestamp(year=year, month=mes, day=20, hour=23, minute=59, second=59)
        return fecha_inicio, fecha_fin
    elif periodo == 3:
        ultimo_dia = calendar.monthrange(year, mes)[1]
        fecha_inicio = pd.Timestamp(year=year, month=mes, day=21, hour=0, minute=0, second=0)
        fecha_fin = pd.Timestamp(year=year, month=mes, day=ultimo_dia, hour=23, minute=59, second=59)
        return fecha_inicio, fecha_fin
    else:
        print(column)
        raise ValueError(f"Fecha invalida, periodo = {periodo}")

In [14]:
c = df_2.columns[11]
print(c)
parse_date_column(c)

2025_041

(Timestamp('2025-04-01 00:00:00'), Timestamp('2025-04-10 23:59:59'))

In [15]:
df_2.head()

,Longitud,Latitud,2025_011,2025_012,2025_013,2025_021,2025_022,2025_023,2025_031,2025_032,...,2025_093,2025_101,2025_102,2025_103,2025_111,2025_112,2025_113,2025_121,2025_122,2025_123
0,-58.3335,-34.3335,44.093086,50.057945,46.926395,55.353222,78.949310,86.827492,97.453812,87.844139,...,96.212311,93.745445,84.110855,84.465073,83.332275,80.154785,75.743927,70.224083,69.450729,53.856770
1,-58.0000,-34.3335,35.933353,40.733299,52.120384,62.594631,78.071442,84.515945,97.780418,88.231819,...,96.243515,93.414093,83.453705,82.806541,77.810364,75.246193,72.772720,68.780899,55.395668,37.541302
2,-58.3335,-34.0000,33.813568,40.265263,42.964825,59.270447,79.005669,86.556381,97.968742,87.838783,...,95.657066,92.798080,81.786568,84.445236,80.598244,83.097298,79.554955,73.763382,66.927856,46.934879
3,-58.0000,-34.0000,33.130894,39.456367,41.439236,59.634979,76.287521,78.027473,97.839584,87.003586,...,95.743652,92.945999,81.534996,82.589813,77.166946,79.708458,74.140434,68.304375,52.428703,36.674797
4,-57.6665,-34.3335,27.766127,30.070860,50.224262,69.234711,75.177559,73.261284,97.453743,87.313469,...,96.316086,93.250900,82.755302,81.633507,74.703522,72.740845,75.224243,64.578918,47.845230,25.843422

In [16]:
longitudes = []
latitudes = []
valores = []
fechas_inicio = []
fechas_fin = []


for i in range(len(df_2)):
    fila = df_2.iloc[i] # <---- # 
    longitud = fila["Longitud"]
    latitud = fila["Latitud"]
    for j in range(2, len(df_2.columns)):
        
        columna = df_2.columns[j] 
        valor = float(fila[columna]) #
        longitudes.append(longitud)
        latitudes.append(latitud)
        valores.append(valor)
        fecha_inicio, fecha_fin = parse_date_column(columna)
        fechas_inicio.append(fecha_inicio)
        fechas_fin.append(fecha_fin)

In [17]:
datos = {
    "longitud": longitudes,
    "latitud": latitud,
    "valor": valores,
    "fecha_inicio": fechas_inicio,
    "fecha_fin": fechas_fin
}
df_test = pd.DataFrame(datos)

In [18]:
df_test

      longitud  latitud      valor fecha_inicio           fecha_fin
0     -58.3335    -34.0  44.093086   2025-01-01 2025-01-10 23:59:59
1     -58.3335    -34.0  50.057945   2025-01-11 2025-01-20 23:59:59
2     -58.3335    -34.0  46.926395   2025-01-21 2025-01-31 23:59:59
3     -58.3335    -34.0  55.353222   2025-02-01 2025-02-10 23:59:59
4     -58.3335    -34.0  78.949310   2025-02-11 2025-02-20 23:59:59
...        ...      ...        ...          ...                 ...
6439  -57.0000    -34.0  69.564087   2025-11-11 2025-11-20 23:59:59
6440  -57.0000    -34.0  65.464714   2025-11-21 2025-11-30 23:59:59
6441  -57.0000    -34.0  51.072136   2025-12-01 2025-12-10 23:59:59
6442  -57.0000    -34.0  58.329884   2025-12-11 2025-12-20 23:59:59
6443  -57.0000    -34.0  30.211380   2025-12-21 2025-12-31 23:59:59

[6444 rows x 5 columns]

In [19]:
# CREATE TYPE granularidad_tipo AS ENUM ('HORA', 'DIA', 'SEMANA', 'MES', 'TRIMESTRE', 'ANIO');

In [21]:
df_2.isnull().sum()

Longitud    0
Latitud     0
2025_011    0
2025_012    0
2025_013    0
2025_021    0
2025_022    0
2025_023    0
2025_031    0
2025_032    0
2025_033    0
2025_041    0
2025_042    0
2025_043    0
2025_051    0
2025_052    0
2025_053    0
2025_061    0
2025_062    0
2025_063    0
2025_071    0
2025_072    0
2025_073    0
2025_081    0
2025_082    0
2025_083    0
2025_091    0
2025_092    0
2025_093    0
2025_101    0
2025_102    0
2025_103    0
2025_111    0
2025_112    0
2025_113    0
2025_121    0
2025_122    0
2025_123    0
dtype: int64